"""
PROGNOS Label Generator
=======================
Maps ground-truth attack labels from CIC-IDS-2017 and CTU-13 datasets
to our Zeek-generated sequences.csv, using MITRE ATT&CK stage taxonomy.

MITRE ATT&CK Classes:
    0 = Normal Traffic
    1 = Reconnaissance
    2 = Initial Access
    3 = Lateral Movement
    4 = Command and Control

Problem Statement Compliance:
    - Maps predicted behaviour to recognised attack stages (MITRE ATT&CK)
    - Covers: Reconnaissance, Initial Access, Lateral Movement, C2
    - Labels derived from official dataset annotations
"""

import pandas as pd
import numpy as np
import argparse
import os
import glob

# ================================================================
# LABEL TRANSLATION MATRIX
# Maps raw dataset labels to MITRE ATT&CK stages.
# This is the critical mapping that ties our model to the rubric.
# ================================================================

CIC_IDS_2017_LABEL_MAP = {
    # Normal
    'BENIGN':                       0,
    'Benign':                       0,

    # Reconnaissance (MITRE TA0043)
    'PortScan':                     1,

    # Initial Access (MITRE TA0001)
    'FTP-Patator':                  2,
    'SSH-Patator':                  2,
    'FTP-BruteForce':               2,
    'SSH-Bruteforce':               2,
    'Web Attack \x96 Brute Force':  2,  # em-dash variant
    'Web Attack - Brute Force':     2,
    'Brute Force -Web':             2,
    'Brute Force -XSS':             2,
    'Web Attack \x96 XSS':          2,
    'Web Attack - XSS':             2,
    'Web Attack \x96 Sql Injection': 2,
    'Web Attack - Sql Injection':   2,
    'SQL Injection':                2,
    'Heartbleed':                   2,

    # Lateral Movement (MITRE TA0008)
    'Infiltration':                 3,
    'Infilteration':                3, # 2018 spelling error in original dataset

    # Command and Control / Impact (MITRE TA0011 / TA0040)
    'Bot':                          4,
    'DDoS':                         4,
    'DDOS attack-LOIC-UDP':         4,
    'DDOS attack-HOIC':             4,
    'DDoS attacks-LOIC-HTTP':       4,
    'DoS slowloris':                4,
    'DoS attacks-Slowloris':        4,
    'DoS Slowhttptest':             4,
    'DoS attacks-SlowHTTPTest':     4,
    'DoS Hulk':                     4,
    'DoS attacks-Hulk':             4,
    'DoS GoldenEye':                4,
    'DoS attacks-GoldenEye':        4,
}

CTU13_BOTNET_IPS = {
    # Scenario 1 (Neris)
    '147.32.84.165': 4,
    # Scenario 2 (Neris)
    '147.32.84.165': 4,
    # Scenario 9 (Neris)
    '147.32.84.165': 4,
    # Scenario 10 (Rbot)
    '147.32.84.165': 4,
}


def label_cic_ids_2017(sequences_csv, labeled_csv_dir, output_path, window_seconds=10):
    """
    Labels sequences.csv using the official CIC-IDS-2017 labeled CSVs.

    The CIC-IDS-2017 dataset ships with per-flow labeled CSVs generated by
    CICFlowMeter. Each row has a Source IP, Timestamp, and Label. We match
    these to our 10-second Zeek windows by:
        1. Parsing the CIC timestamp and flooring it to the nearest 10s window
        2. Mapping the CIC label to a MITRE ATT&CK integer
        3. Joining on (Source IP, Window Timestamp) with our sequences.csv
        4. For windows with mixed traffic, the most severe label wins
    """
    print(f"Loading sequences from: {sequences_csv}")
    seq_df = pd.read_csv(sequences_csv)

    # Ensure timestamp column exists and is parsed
    if 'ts' in seq_df.columns:
        seq_df['ts'] = pd.to_datetime(seq_df['ts'])
    else:
        print("Error: sequences.csv has no 'ts' column.")
        return

    # Initialize labels
    seq_df['mitre_label'] = 0
    seq_df['infiltration_prob'] = 0.0

    # Find all labeled CSVs in the directory
    csv_files = glob.glob(os.path.join(labeled_csv_dir, '*.csv'))
    if not csv_files:
        print(f"Error: No CSV files found in {labeled_csv_dir}")
        return

    print(f"Found {len(csv_files)} labeled CSV files.")

    for csv_file in csv_files:
        print(f"  Processing: {os.path.basename(csv_file)}")
        try:
            # CIC-IDS-2017 CSVs have inconsistent column names with leading spaces
            label_df = pd.read_csv(csv_file, encoding='utf-8', low_memory=False)
        except Exception as e:
            print(f"    Skipping (read error): {e}")
            continue

        # Normalize column names: strip whitespace
        label_df.columns = label_df.columns.str.strip()

        # Identify the key columns (they vary across dataset versions)
        src_col = None
        ts_col = None
        label_col = None

        for col in label_df.columns:
            col_lower = col.lower()
            if 'source ip' in col_lower or col_lower == 'src_ip':
                src_col = col
            elif 'timestamp' in col_lower:
                ts_col = col
            elif col_lower == 'label':
                label_col = col

        if not all([src_col, ts_col, label_col]):
            print(f"    Skipping (missing columns). Found: src={src_col}, ts={ts_col}, label={label_col}")
            continue

        # Parse timestamps
        label_df[ts_col] = pd.to_datetime(label_df[ts_col], errors='coerce', dayfirst=True)
        label_df = label_df.dropna(subset=[ts_col])

        # Map labels to MITRE
        label_df['mitre'] = label_df[label_col].str.strip().map(CIC_IDS_2017_LABEL_MAP)
        label_df['mitre'] = label_df['mitre'].fillna(0).astype(int)

        # Floor timestamps to 10-second windows
        label_df['window_ts'] = label_df[ts_col].dt.floor(f'{window_seconds}s')

        # For each (Source IP, Window), take the MAXIMUM severity label
        # This ensures that if even one attack flow exists in a window, it gets flagged
        malicious = label_df[label_df['mitre'] > 0]
        if len(malicious) == 0:
            print(f"    No attack flows found in this file.")
            continue

        window_labels = malicious.groupby([src_col, 'window_ts'])['mitre'].max().reset_index()
        window_labels.columns = ['src_ip', 'window_ts', 'mitre_stage']

        print(f"    Found {len(window_labels)} malicious windows across {window_labels['src_ip'].nunique()} IPs.")

        # Match with our sequences
        if 'id.orig_h' in seq_df.columns:
            seq_df['window_ts'] = seq_df['ts'].dt.floor(f'{window_seconds}s')

            # Merge: left join so we keep all sequence rows
            merged = seq_df.merge(
                window_labels,
                left_on=['id.orig_h', 'window_ts'],
                right_on=['src_ip', 'window_ts'],
                how='left'
            )

            # Update labels where we found a match
            mask = merged['mitre_stage'].notna()
            seq_df.loc[mask, 'mitre_label'] = merged.loc[mask, 'mitre_stage'].astype(int)
            seq_df.loc[mask, 'infiltration_prob'] = 1.0

            # Clean up temp column
            if 'window_ts' in seq_df.columns:
                seq_df.drop(columns=['window_ts'], inplace=True)
            if 'mitre_stage' in merged.columns:
                merged.drop(columns=['mitre_stage', 'src_ip'], inplace=True, errors='ignore')

    # Print summary
    print("\n--- Label Distribution ---")
    label_names = {0: 'Normal', 1: 'Reconnaissance', 2: 'Initial Access', 3: 'Lateral Movement', 4: 'C2'}
    for val, name in label_names.items():
        count = (seq_df['mitre_label'] == val).sum()
        pct = count / len(seq_df) * 100
        print(f"  {name}: {count:,} ({pct:.1f}%)")

    # Save
    seq_df.to_csv(output_path, index=False)
    print(f"\nSaved labeled sequences to: {output_path}")


def label_ctu13(sequences_csv, output_path):
    """
    Labels sequences.csv using known CTU-13 botnet IP addresses.

    CTU-13 does not ship per-flow CSVs in the same format as CIC-IDS-2017.
    Instead, the infected machine's IP is documented. Every flow originating
    from the botnet IP is labeled as MITRE Stage 4 (Command and Control).
    All other traffic is Normal (0).
    """
    print(f"Loading sequences from: {sequences_csv}")
    seq_df = pd.read_csv(sequences_csv)

    seq_df['mitre_label'] = 0
    seq_df['infiltration_prob'] = 0.0

    if 'id.orig_h' in seq_df.columns:
        for ip, label in CTU13_BOTNET_IPS.items():
            mask = seq_df['id.orig_h'] == ip
            count = mask.sum()
            if count > 0:
                seq_df.loc[mask, 'mitre_label'] = label
                seq_df.loc[mask, 'infiltration_prob'] = 1.0
                print(f"  Labeled {count:,} windows from botnet IP {ip} as C2.")

    # Print summary
    print("\n--- Label Distribution ---")
    label_names = {0: 'Normal', 1: 'Reconnaissance', 2: 'Initial Access', 3: 'Lateral Movement', 4: 'C2'}
    for val, name in label_names.items():
        count = (seq_df['mitre_label'] == val).sum()
        pct = count / len(seq_df) * 100
        print(f"  {name}: {count:,} ({pct:.1f}%)")

    seq_df.to_csv(output_path, index=False)
    print(f"\nSaved labeled sequences to: {output_path}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Label PROGNOS sequences with MITRE ATT&CK stages.")
    parser.add_argument('--mode', type=str, required=True, choices=['cic', 'ctu13'],
                        help="Dataset mode: 'cic' for CIC-IDS-2017, 'ctu13' for CTU-13 botnet")
    parser.add_argument('--sequences', type=str, required=True,
                        help="Path to the unlabeled sequences.csv")
    parser.add_argument('--labels', type=str, default=None,
                        help="Path to directory containing CIC-IDS-2017 labeled CSVs (required for --mode cic)")
    parser.add_argument('--output', type=str, required=True,
                        help="Path to save the labeled output CSV")
    parser.add_argument('--window', type=int, default=10,
                        help="Window size in seconds (must match sequence_chunker)")

    args = parser.parse_args()

    if args.mode == 'cic':
        if not args.labels:
            print("Error: --labels directory is required for CIC-IDS-2017 mode.")
            exit(1)
        label_cic_ids_2017(args.sequences, args.labels, args.output, args.window)
    elif args.mode == 'ctu13':
        label_ctu13(args.sequences, args.output)
