"""
PROGNOS Label Generator
=======================
Maps ground-truth attack labels from CIC-IDS-2017 and CTU-13 datasets
to our Zeek-generated sequences.csv, using MITRE ATT&CK stage taxonomy.

MITRE ATT&CK Classes:
    0 = Normal Traffic
    1 = Reconnaissance
    2 = Initial Access
    3 = Lateral Movement
    4 = Command and Control

Problem Statement Compliance:
    - Maps predicted behaviour to recognised attack stages (MITRE ATT&CK)
    - Covers: Reconnaissance, Initial Access, Lateral Movement, C2
    - Labels derived from official dataset annotations
"""

import pandas as pd
import numpy as np
import argparse
import os
import glob

# ================================================================
# LABEL TRANSLATION MATRIX
# Maps raw dataset labels to MITRE ATT&CK stages.
# This is the critical mapping that ties our model to the rubric.
# ================================================================

CIC_IDS_2017_LABEL_MAP = {
    # Normal
    'BENIGN':                       0,
    'Benign':                       0,

    # Reconnaissance (MITRE TA0043)
    'PortScan':                     1,

    # Initial Access (MITRE TA0001)
    'FTP-Patator':                  2,
    'SSH-Patator':                  2,
    'FTP-BruteForce':               2,
    'SSH-Bruteforce':               2,
    'Web Attack \x96 Brute Force':  2,  # em-dash variant
    'Web Attack - Brute Force':     2,
    'Brute Force -Web':             2,
    'Brute Force -XSS':             2,
    'Web Attack \x96 XSS':          2,
    'Web Attack - XSS':             2,
    'Web Attack \x96 Sql Injection': 2,
    'Web Attack - Sql Injection':   2,
    'SQL Injection':                2,
    'Heartbleed':                   2,

    # Lateral Movement (MITRE TA0008)
    'Infiltration':                 3,
    'Infilteration':                3, # 2018 spelling error in original dataset

    # Command and Control / Impact (MITRE TA0011 / TA0040)
    'Bot':                          4,
    'DDoS':                         4,
    'DDOS attack-LOIC-UDP':         4,
    'DDOS attack-HOIC':             4,
    'DDoS attacks-LOIC-HTTP':       4,
    'DoS slowloris':                4,
    'DoS attacks-Slowloris':        4,
    'DoS Slowhttptest':             4,
    'DoS attacks-SlowHTTPTest':     4,
    'DoS Hulk':                     4,
    'DoS attacks-Hulk':             4,
    'DoS GoldenEye':                4,
    'DoS attacks-GoldenEye':        4,
}

CTU13_BOTNET_IPS = {
    # Scenario 1 (Neris)
    '147.32.84.165': 4,
    # Scenario 2 (Neris)
    '147.32.84.165': 4,
    # Scenario 9 (Neris)
    '147.32.84.165': 4,
    # Scenario 10 (Rbot)
    '147.32.84.165': 4,
}


def label_cic_ids_2017(sequences_csv, labeled_csv_dir, output_path, window_seconds=10):
    """
    Labels sequences.csv using the official CIC-IDS-2017 labeled CSVs.

    The CIC-IDS-2017 dataset ships with per-flow labeled CSVs generated by
    CICFlowMeter. Each row has a Source IP, Timestamp, and Label. We match
    these to our 10-second Zeek windows by:
        1. Parsing the CIC timestamp and flooring it to the nearest 10s window
        2. Mapping the CIC label to a MITRE ATT&CK integer
        3. Joining on (Source IP, Window Timestamp) with our sequences.csv
        4. For windows with mixed traffic, the most severe label wins
    """
    # Find all labeled CSVs in the directory
    csv_files = glob.glob(os.path.join(labeled_csv_dir, '*.csv'))
    if not csv_files:
        print(f"Error: No CSV files found in {labeled_csv_dir}")
        return

    print(f"Found {len(csv_files)} labeled CSV files. Compiling attack database first...")
    
    all_malicious_windows = []

    for csv_file in csv_files:
        try:
            label_df = pd.read_csv(csv_file, encoding='utf-8', low_memory=False)
        except Exception as e:
            continue

        label_df.columns = label_df.columns.str.strip()
        src_col, ts_col, label_col = None, None, None

        for col in label_df.columns:
            col_lower = col.lower()
            if 'source ip' in col_lower or col_lower == 'src_ip' or 'src ip' in col_lower:
                src_col = col
            elif 'timestamp' in col_lower:
                ts_col = col
            elif col_lower == 'label':
                label_col = col

        if not all([src_col, ts_col, label_col]):
            print(f"    Skipping (missing columns). Found: src={src_col}, ts={ts_col}, label={label_col}")
            continue

        label_df[ts_col] = pd.to_datetime(label_df[ts_col], errors='coerce', dayfirst=True)
        label_df = label_df.dropna(subset=[ts_col])
        label_df['mitre'] = label_df[label_col].str.strip().map(CIC_IDS_2017_LABEL_MAP).fillna(0).astype(int)
        
        malicious = label_df[label_df['mitre'] > 0]
        if len(malicious) > 0:
            window_labels = malicious.groupby(src_col)['mitre'].max().reset_index()
            window_labels.columns = ['src_ip', 'mitre_stage']
            all_malicious_windows.append(window_labels)

    if not all_malicious_windows:
        print("Error: No malicious traffic found in the label CSVs!")
        return
        
    master_attack_db = pd.concat(all_malicious_windows, ignore_index=True)
    master_attack_db = master_attack_db.groupby('src_ip')['mitre_stage'].max().reset_index()
    print(f"Built Attack Database: {len(master_attack_db)} unique attacker IPs found.")

    print(f"\nStreaming massive sequences file: {sequences_csv}")
    print("Labeling in chunks to prevent RAM overflow...")
    
    chunksize = 2_000_000
    first_write = True
    total_processed = 0
    label_counts = {0: 0, 1: 0, 2: 0, 3: 0, 4: 0}
    
    for chunk in pd.read_csv(sequences_csv, chunksize=chunksize):
        if 'ts' not in chunk.columns:
            print("Error: sequences.csv has no 'ts' column.")
            return
            
        chunk['ts'] = pd.to_datetime(chunk['ts'])
        chunk['mitre_label'] = 0
        chunk['infiltration_prob'] = 0.0
        
        if 'id.orig_h' in chunk.columns:
            
            merged = chunk.merge(
                master_attack_db,
                left_on='id.orig_h',
                right_on='src_ip',
                how='left'
            )
            
            # Use .values to ignore index misalignment between chunk and merged
            chunk['mitre_stage_tmp'] = merged['mitre_stage'].values
            mask = chunk['mitre_stage_tmp'].notna()
            
            chunk.loc[mask, 'mitre_label'] = chunk.loc[mask, 'mitre_stage_tmp'].astype(int)
            chunk.loc[mask, 'infiltration_prob'] = 1.0
            chunk.drop(columns=['window_ts', 'mitre_stage_tmp'], inplace=True, errors='ignore')

        # Track distributions
        counts = chunk['mitre_label'].value_counts()
        for k, v in counts.items():
            label_counts[k] += v

        # Stream to disk
        mode = 'w' if first_write else 'a'
        header = True if first_write else False
        chunk.to_csv(output_path, mode=mode, header=header, index=False)
        
        total_processed += len(chunk)
        print(f"  ... Labeled {total_processed:,} rows")
        first_write = False

    print("\n--- Final Label Distribution ---")
    label_names = {0: 'Normal', 1: 'Reconnaissance', 2: 'Initial Access', 3: 'Lateral Movement', 4: 'C2'}
    for val, name in label_names.items():
        count = label_counts.get(val, 0)
        pct = (count / total_processed * 100) if total_processed > 0 else 0
        print(f"  {name}: {count:,} ({pct:.1f}%)")

    print(f"\nSaved seamlessly to: {output_path}")


def label_ctu13(sequences_csv, output_path):
    """
    Labels sequences.csv using known CTU-13 botnet IP addresses.

    CTU-13 does not ship per-flow CSVs in the same format as CIC-IDS-2017.
    Instead, the infected machine's IP is documented. Every flow originating
    from the botnet IP is labeled as MITRE Stage 4 (Command and Control).
    All other traffic is Normal (0).
    """
    print(f"Loading sequences from: {sequences_csv}")
    seq_df = pd.read_csv(sequences_csv)

    seq_df['mitre_label'] = 0
    seq_df['infiltration_prob'] = 0.0

    if 'id.orig_h' in seq_df.columns:
        for ip, label in CTU13_BOTNET_IPS.items():
            mask = seq_df['id.orig_h'] == ip
            count = mask.sum()
            if count > 0:
                seq_df.loc[mask, 'mitre_label'] = label
                seq_df.loc[mask, 'infiltration_prob'] = 1.0
                print(f"  Labeled {count:,} windows from botnet IP {ip} as C2.")

    # Print summary
    print("\n--- Label Distribution ---")
    label_names = {0: 'Normal', 1: 'Reconnaissance', 2: 'Initial Access', 3: 'Lateral Movement', 4: 'C2'}
    for val, name in label_names.items():
        count = (seq_df['mitre_label'] == val).sum()
        pct = count / len(seq_df) * 100
        print(f"  {name}: {count:,} ({pct:.1f}%)")

    seq_df.to_csv(output_path, index=False)
    print(f"\nSaved labeled sequences to: {output_path}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Label PROGNOS sequences with MITRE ATT&CK stages.")
    parser.add_argument('--mode', type=str, required=True, choices=['cic', 'ctu13'],
                        help="Dataset mode: 'cic' for CIC-IDS-2017, 'ctu13' for CTU-13 botnet")
    parser.add_argument('--sequences', type=str, required=True,
                        help="Path to the unlabeled sequences.csv")
    parser.add_argument('--labels', type=str, default=None,
                        help="Path to directory containing CIC-IDS-2017 labeled CSVs (required for --mode cic)")
    parser.add_argument('--output', type=str, required=True,
                        help="Path to save the labeled output CSV")
    parser.add_argument('--window', type=int, default=10,
                        help="Window size in seconds (must match sequence_chunker)")

    args = parser.parse_args()

    if args.mode == 'cic':
        if not args.labels:
            print("Error: --labels directory is required for CIC-IDS-2017 mode.")
            exit(1)
        label_cic_ids_2017(args.sequences, args.labels, args.output, args.window)
    elif args.mode == 'ctu13':
        label_ctu13(args.sequences, args.output)
