[project]
name = "prognos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nisarg", email = "nisarg34.bhatt@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "scapy>=2.7.0",
    "scikit-learn>=1.9.0",
    "shap>=0.52.0",
    "uvicorn>=0.52.4",
    "xgboost>=3.4.1",
]

[project.scripts]
prognos = "prognos:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
